config/routes.rb
GoodForm::Application.routes.draw do
  devise_for :users

  resources :goodForms do
	resources :leagues
	resources :statistics
	resources :games
	resources :predictions
  end

  
  

  authenticated :user do
	root :to => 'goodForms#index'
  end
  
  unauthenticated :user do
	devise_scope :user do
		get "/" => "devise/sessions#new"
	end
  end
  
  resources :games
  root to: 'games#index'
  
  resources :teams
   root to: 'teams#index'
   
 
  resources :leagues
   root to: 'leagues#index'
end

app/controllers/good_forms_controller.rb
class GoodFormsController < ApplicationController
	def index
		@teams = Team.search(params[:search])
		@leagues = League.search(params[:leagueSearch])
		@gamesForToday = Game.search()
	end
	
	def show
		@team        = Team.find(params[:id])
		@games       = Game.where("team1 = ? OR team2 = ?", @team.id, @team.id) #Returns an array 
		@gamesSorted = @games.all(:order => "kodate DESC")
		#@statistics = Statistic.find(@games.first.team1.id) # find the statistics for the first game.
		@teamsInSameleague = Team.where("name = ?", @games.first.league.name)
		
		
		#Find the statistics for the games for the team with team.id (1) or team.id (2)
		#Then aggregate the stats and find averages.
		
		@totalHomeGoals            = 0
		@totalAwayGoals            = 0
		@totalHomeCorners          = 0
		@totalAwayCorners          = 0
		@totalHomeAttacks          = 0
		@totalAwayAttacks          = 0
		@totalHomeDangerousAttacks = 0
		@totalAwayDangerousAttacks = 0
		@totalHomeShotsOnTarget    = 0
		@totalAwayShotsOnTarget    = 0
		@totalHomeShotsOffTarget   = 0
		@totalAwayShotsOffTarget   = 0

		@homeGames = Game.where("team1 = ?", @team.id)
		
		@homeGames.each do |hgame|
			@homeStats = Statistic.where("game_id = ?", hgame.id)
			
			if !@homeStats.empty?
				unless @homeStats.last.hg.nil?
					@totalHomeGoals            += @homeStats.last.hg
				end
				unless @homeStats.last.hco.nil?
					@totalHomeCorners          += @homeStats.last.hco
				end
				unless @homeStats.last.ha.nil?
					@totalHomeAttacks          += @homeStats.last.ha
				end
				unless @homeStats.last.hda.nil?
					@totalHomeDangerousAttacks += @homeStats.last.hda
				end
				unless @homeStats.last.hsont.nil?
					@totalHomeShotsOnTarget    += @homeStats.last.hsont
				end
				unless @homeStats.last.hsofft.nil?
					@totalHomeShotsOffTarget   += @homeStats.last.hsofft
				end
			end
		end

		@awayGames = Game.where("team2 = ?", @team.id)
		
		@awayGames.each do |agame|
			@awayStats = Statistic.where("game_id = ?", agame.id)
			
			if !@awayStats.empty?
				unless @awayStats.last.ag.nil?
					@totalAwayGoals            += @awayStats.last.ag
				end
				unless @awayStats.last.aco.nil?
					@totalAwayCorners          += @awayStats.last.aco
				end
				unless @awayStats.last.aa.nil?
					@totalAwayAttacks          += @awayStats.last.aa
				end
				unless @awayStats.last.ada.nil?
					@totalAwayDangerousAttacks += @awayStats.last.ada
				end
				unless @awayStats.last.asont.nil?
					@totalAwayShotsOnTarget    += @awayStats.last.asont
				end
				unless @awayStats.last.asofft.nil?
					@totalAwayShotsOffTarget   += @awayStats.last.asofft
				end
			end
		end
		
		@homeGamesPlayed = @homeGames.size
		@awayGamesPlayed = @awayGames.size
		
		@totalCorners                = @totalHomeCorners+@totalAwayCorners
		
		@averageHomeGoals            = @totalHomeGoals.to_f/@homeGamesPlayed
		@averageAwayGoals            = @totalAwayGoals.to_f/@awayGamesPlayed
		
		@averageHomeCorners          = @totalHomeCorners.to_f/@homeGamesPlayed
		@averageAwayCorners          = @totalAwayCorners.to_f/@awayGamesPlayed

		@averageHomeAttacks          = @totalHomeAttacks.to_f/@homeGamesPlayed
		@averageAwayAttacks          = @totalAwayAttacks.to_f/@awayGamesPlayed

		@averageHomeDangerousAttacks = @totalHomeDangerousAttacks.to_f/@homeGamesPlayed
		@averageAwayDangerousAttacks = @totalAwayDangerousAttacks.to_f/@awayGamesPlayed

		@averageHomeShotsOnTarget    = @totalHomeShotsOnTarget.to_f/@homeGamesPlayed
		@averageAwayShotsOnTarget    = @totalAwayShotsOnTarget.to_f/@awayGamesPlayed
		
		@averageHomeShotsOffTarget   = @totalHomeShotsOffTarget.to_f/@homeGamesPlayed
		@averageAwayShotsOffTarget   = @totalAwayShotsOffTarget.to_f/@awayGamesPlayed
	end
	
	def new
	
	end
	
	def create
	
	end
	
	def edit
	
	end
	
	def update
	
	end
	
	def destroy
	
	end
end

app/helpers/good_forms_helper.rb
module GoodFormsHelper
end

app/views/good_forms/index.html.erb
<meta http-equiv="refresh" content="60" />

<h1>Good Form</h1>

<% d = Time.zone.now %>

<p>
	Time: <%= d.strftime('%b %d, %Y %H:%M:%S') =%>
</p>

<!-- <table border="1">
	<tr>
		<td>Teams</td>
		<td>Leagues</td>
		<td>Games</td>
		<td>Statistics Available</td>
	</tr>
	<tr>
		<td><%= @numberOfTeams %></td>
		<td><%= @numberOfLeagues %></td>
		<td><%= @NumberOfGames %></td>
		<td><%= @numberOfStatistics %></td>
	</tr>
</table> -->

<a name"top"></a>

<p>
	<b>Current and Upcoming Games</b> (inc. games in the last 2 hours):
</p>

<table id="games" class="display" data-source="<%= games_url(format: "json") %>">

	<thead>
		<tr>
			<th>Kick Off Time</th>
			<th>Home Team</th>
			<th>Away Team</th>
			<th>Predictions</th>
			<th>Statistics</th>

		</tr>
	</thead>

	<tbody></tbody>
</table>

<table id="teams" class="display" data-source="<%= teams_url(format: "json") %>">
	<thead>
		<tr>
			<th>Team Name</th>
		</tr>
	</thead>
	<tbody></tbody>
</table>

<table id="leagues" class="display" data-source="<%= leagues_url(format: "json") %>">
	<thead>
		<tr>
			<th>League Name</th>
		</tr>
	</thead>
	<tbody></tbody>
</table>

<p>
	<a href="#top">Back To Top</a>
</p>

app/views/good_forms/show.html.erb
<h1><%= @team.name %></h1>

<table border="1" id="summary">

<p>Good Form has records for <%= @homeGamesPlayed %> Home games and <%= @awayGamesPlayed %> Away games </p>

  <tr>
    <th>Average</th>
    <th>Home</th>
    <th>Away</th>
  </tr>
  <tr>
    <td>Goals Scored</td>
    <td><%= @averageHomeGoals.round(1) %></td>
    <td><%= @averageAwayGoals.round(1) %></td>
  </tr>
  <tr>
    <td>Corners</td>
    <td><%= @averageHomeCorners.round(1) %></td>
    <td><%= @averageAwayCorners.round(1) %></td>
  </tr>
  <tr>
    <td>Attacks</td>
    <td><%= @averageHomeAttacks.round(1) %></td>
    <td><%= @averageAwayAttacks.round(1) %></td>
  </tr>
  <tr>
    <td>Dangerous Attacks</td>
    <td><%= @averageHomeDangerousAttacks.round(1) %></td>
    <td><%= @averageAwayDangerousAttacks.round(1) %></td>
  </tr>
  <tr>
    <td>Shots On Target</td>
    <td><%= @averageHomeShotsOnTarget.round(1) %></td>
    <td><%= @averageAwayShotsOnTarget.round(1) %></td>
  </tr>
  <tr>
    <td>Shots Off Target</td>
    <td><%= @averageHomeShotsOffTarget.round(1) %></td>
    <td><%= @averageAwayShotsOffTarget.round(1) %></td>
  </tr>
</table>

<br> </br>

<table border="1" id="games">

<h2><b>Games</b></h2>

<b>Key</b><p/>
<b>HWL</b> : Home Win Likelihood,
<b>HG</b> :  Home Goals (Actual, where applicable),
<b>PHG</b>:  Predicted Home Goals,
<b>HCWL</b> : Home Corner Win Likelihood,
<b>HC</b> :  Home Corners (Actual, where applicable),
<b>PHC</b> : Predicted Home Corners,
<b>AWL</b> : Away Win Likelihood,
<b>AG</b> :  Away Goals (Actual, where applicable),
<b>PAG</b> : Predicted Away Goals,
<b>ACWL</b> : Away Corner Win Likelihood,
<b>AC</b> :  Away Corners (Actual, where applicable),
<b>PAC</b> : Predicted Away Corners.
<p></p>

<tr>
	<th>League</th>
	<th>Kick Off Date</th>
	<th>Home Team</th>
	<th>HWL</th>
	<th>HG</th>
	<th>PHG</th>
	<th>HCWL</th>
	<th>HC</th>
	<th>PHC</th>
	<th>Away Team</th>
	<th>AWL</th>
	<th>AG</th>
	<th>PAG</th>
	<th>ACWL</th>
	<th>AC</th>
	<th>PAC</th>
	<th>Statistics</th>
</tr>
	<% @gamesSorted.each do |game| %>
		<% @gameStats       = Statistic.where("game_id = ?", game.id).last %>
		<% @gamePredictions = PredictionData.where("gameid = ?", game.id).last %>
<tr>
	<td><%= link_to game.league.name, goodForm_league_path(game.league_id) %></td>
	<td><%= game.kodate.strftime('%b %d, %Y %H:%M:%S') %></td>
	<td><%= link_to game.team1.name, goodForm_path(game.team1)%></td>
	<td><% if @gamePredictions %>
			<%= @gamePredictions.goalswinhome.round(3) %> <!-- HWL -->
		<%end%>		
	</td>
	<td>
		<% if @gameStats %>
			<%= @gameStats.hg %> <!-- HG -->
		<% end %>
	</td>
	<td><% if @gamePredictions %>
			<%= @gamePredictions.goalslikelyscorehome %> <!-- PHG -->
		<%end%>
	</td>
	<td><% if @gamePredictions %>
			<%= @gamePredictions.cornerswinhome.round(3) %> <!-- HCWL -->
		<%end%>
	</td>
	<td>
		<% if @gameStats %>
			<%= @gameStats.hco %> <!-- HC -->
		<% end %>
	</td>		
	<td><% if @gamePredictions %>
			<%= @gamePredictions.cornerslikelyscorehome.round(3) %> <!--PHC -->
		<% end %>
	</td>					
	<td><%= link_to game.team2.name, goodForm_path(game.team2) %> </td>
	<td><% if @gamePredictions %>
			<%= @gamePredictions.goalswinaway.round(3) %> <!-- AWL -->
		<%end%>		
	</td>
	<td>
		<% if @gameStats %> 
			<%= @gameStats.ag %> <!-- AG -->
		<% end %>
	</td>
	<td><% if @gamePredictions %>
				<%= @gamePredictions.goalslikelyscoreaway.round(3) %> <!--PAG -->
		<% end %>
	</td>
	<td><% if @gamePredictions %>
			<%= @gamePredictions.cornerswinaway.round(3) %> <!-- ACWL -->
		<%end%>
	</td>
	<td>
		<% if @gameStats %>
			<%= @gameStats.aco %> <!-- AC -->
		<% end %>
	</td>	
	<td><% if @gamePredictions %>
				<%= @gamePredictions.cornerslikelyscoreaway.round(3) %> <!-- PAC -->
		<% end %>
	</td>
		<% if @gameStats %>
			<td><%= link_to "Click for Statistics", goodForm_statistics_path(game)%></td>
		<% else %>
			<td> :( no stats available</td>
		<% end %>
</tr>
	<% end %>
</table>

<small><%= @team.created_at %></small>